/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;


public class control_asistencia extends JFrame {
private ImageIcon imagenInicio, imagenClose, imagenRest, imagenMin;
private Icon icono, icono_close,icono_Rest,icono_Min;
private ButtonGroup grupoBtn;
private JLabel etipass;
private JPasswordField txtpas;

    /**
     * Creates new form control_asistencia
     */
    public control_asistencia() {
        initComponents();
        setSize(800,600);
        getContentPane().setBackground(Color.decode("#E4E4E4"));
        etiImagenI.setBackground(Color.decode("#E4E4E4"));
        jPanel1.setBackground(Color.decode("#95989A"));
        tgbtnEntrada.setBackground(Color.decode("#549788"));
        tgbtnSalida.setBackground(Color.decode("#DC4D41"));
        btnRegist.setBackground(Color.decode("#0078D7"));
        btnSesion.setBackground(Color.decode("#0078D7"));
        jSeparator2.setBackground(Color.decode("#95989A"));
        setLocationRelativeTo(null);
        
        grupoBtn = new ButtonGroup();
        grupoBtn.add(tgbtnEntrada);
        grupoBtn.add(tgbtnSalida);
        
        imagenInicio = new ImageIcon("src/imagenes/iconLogin.png");
        icono = new ImageIcon(imagenInicio.getImage().getScaledInstance(etiImagenI.getWidth(), etiImagenI.getHeight(), Image.SCALE_DEFAULT));
        etiImagenI.setIcon(icono);
                
        imagenClose = new ImageIcon("src/imagenes/btnClose.png");
        icono_close = new ImageIcon(imagenClose.getImage().getScaledInstance(etiClose.getWidth(), etiClose.getHeight(), Image.SCALE_DEFAULT));
        etiClose.setIcon(icono_close);
        
        imagenRest = new ImageIcon("src/imagenes/rest.png");
        icono_Rest = new ImageIcon(imagenRest.getImage().getScaledInstance(etiRest.getWidth(), etiRest.getHeight(), Image.SCALE_DEFAULT));
        etiRest.setIcon(icono_Rest);
        
        imagenMin = new ImageIcon("src/imagenes/mini.png");
        icono_Min = new ImageIcon(imagenMin.getImage().getScaledInstance(etimin.getWidth(), etimin.getHeight(), Image.SCALE_DEFAULT));
        etimin.setIcon(icono_Min);  
        
        etiError.setVisible(false);
        etipass = new JLabel("Password");
        etipass.setBounds(20, 100, 101, 14);
        txtpas= new JPasswordField();
        txtpas.setBounds(20, 120, 204, 30);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jToolBar1 = new javax.swing.JToolBar();
        etiImagenI = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        etiClose = new javax.swing.JLabel();
        etiRest = new javax.swing.JLabel();
        etimin = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        etiError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        tgbtnEntrada = new javax.swing.JToggleButton();
        tgbtnSalida = new javax.swing.JToggleButton();
        btnRegist = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSesion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        etiEvent = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        etiImagenI.setBackground(new java.awt.Color(204, 204, 204));
        etiImagenI.setFocusTraversalPolicyProvider(true);
        etiImagenI.setOpaque(true);
        getContentPane().add(etiImagenI);
        etiImagenI.setBounds(80, 150, 250, 250);

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));

        etiClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiCloseMouseExited(evt);
            }
        });

        etiRest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiRestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiRestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiRestMouseExited(evt);
            }
        });

        etimin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiminMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(718, Short.MAX_VALUE)
                .addComponent(etimin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiRest, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etimin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiRest, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 42);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator2.setOpaque(true);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(401, 49, 3, 683);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese Datos"));
        jPanel1.setOpaque(false);

        etiError.setForeground(new java.awt.Color(255, 0, 0));
        etiError.setText("Numero de control incorrecto");

        jLabel1.setText("Codigo de Empleado:");

        tgbtnEntrada.setText("Entrada");

        tgbtnSalida.setText("Salida");

        btnRegist.setText("Registrarme");
        btnRegist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(etiError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tgbtnSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegist))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tgbtnEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgbtnEntrada)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgbtnSalida))
                .addGap(27, 27, 27)
                .addComponent(btnRegist)
                .addGap(24, 24, 24)
                .addComponent(etiError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(35, 410, 335, 262);
        getContentPane().add(jCalendar1);
        jCalendar1.setBounds(424, 178, 360, 268);

        jLabel3.setText("Hoy:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(440, 470, 40, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Iniciar Sesion");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 90, 157, 49);

        btnSesion.setText("Iniciar Sesion");
        btnSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnSesion);
        btnSesion.setBounds(670, 660, 110, 30);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        etiEvent.setText("Sin Eventos ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiEvent)
                .addContainerGap(281, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiEvent)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(430, 490, 350, 156);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etiCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiCloseMouseEntered
      ImageIcon imagen = new ImageIcon("src/imagenes/btnClose2.png");
       Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(etiClose.getWidth(), etiClose.getHeight(), Image.SCALE_DEFAULT));
        etiClose.setIcon(icono);
    }//GEN-LAST:event_etiCloseMouseEntered

    private void etiCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiCloseMouseExited
       ImageIcon imagen = new ImageIcon("src/imagenes/btnClose.png");
       Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(etiClose.getWidth(), etiClose.getHeight(), Image.SCALE_DEFAULT));
        etiClose.setIcon(icono);
    }//GEN-LAST:event_etiCloseMouseExited

    private void etiCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiCloseMouseClicked
    //if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
      //  "Salir del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        System.exit(0);
    }//GEN-LAST:event_etiCloseMouseClicked

    private void etiRestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiRestMouseEntered
       ImageIcon imagen = new ImageIcon("src/imagenes/rest2.png");
       Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(etiRest.getWidth(), etiRest.getHeight(), Image.SCALE_DEFAULT));
        etiRest.setIcon(icono);
    }//GEN-LAST:event_etiRestMouseEntered

    private void etiRestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiRestMouseExited
        ImageIcon imagen = new ImageIcon("src/imagenes/rest.png");
       Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(etiRest.getWidth(), etiRest.getHeight(), Image.SCALE_DEFAULT));
        etiRest.setIcon(icono);  // TODO add your handling code here:
    }//GEN-LAST:event_etiRestMouseExited

    private void etiRestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiRestMouseClicked
         /*if(getExtendedState() == JFrame.MAXIMIZED_BOTH){//1
            setExtendedState(JFrame.NORMAL);//2
        }else
            setExtendedState(JFrame.MAXIMIZED_BOTH);//3*/
    }//GEN-LAST:event_etiRestMouseClicked

    private void etiminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiminMouseEntered
       ImageIcon imagen = new ImageIcon("src/imagenes/mini2.png");
       Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(etimin.getWidth(), etimin.getHeight(), Image.SCALE_DEFAULT));
        etimin.setIcon(icono);
    }//GEN-LAST:event_etiminMouseEntered

    private void etiminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiminMouseExited
       ImageIcon imagen = new ImageIcon("src/imagenes/mini.png");
       Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(etimin.getWidth(), etimin.getHeight(), Image.SCALE_DEFAULT));
       etimin.setIcon(icono); // TODO add your handling code here:
    }//GEN-LAST:event_etiminMouseExited

    private void etiminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiminMouseClicked
       setExtendedState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_etiminMouseClicked

    private void btnSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesionActionPerformed
             
        if(evt.getActionCommand().equals("Iniciar Sesion")){ 
        jPanel1.remove(tgbtnEntrada);
        jPanel1.remove(tgbtnSalida);
        jPanel1.add(etipass);
        jPanel1.add(txtpas);
        btnSesion.setText("<< Regresar");
        jPanel1.repaint();
        }
       else{
        jPanel1.add(tgbtnEntrada);
        jPanel1.add(tgbtnSalida);    
        jPanel1.remove(etipass);
        jPanel1.remove(txtpas);
        btnSesion.setText("Iniciar Sesion");
        jPanel1.repaint();
       }
        jTextField1.setText("");
        txtpas.setText("");
    }//GEN-LAST:event_btnSesionActionPerformed

    private void btnRegistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistActionPerformed
       Login_Entrada entro = new Login_Entrada();
       Menu_Control entro1 = new Menu_Control();
        if(btnSesion.getActionCommand().equals("<< Regresar")){
        if(txtpas.getText().equals("luis")){
            entro1.setVisible(true);
        }
        else
            etiError.setVisible(true);
        }
        else{
            etiError.setVisible(false);
            entro.setVisible(true);
            if(tgbtnEntrada.isSelected())
                entro.llegada(true);
            else
                entro.llegada(false);
            
        }
        jTextField1.setText("");
        txtpas.setText("");
            
    }//GEN-LAST:event_btnRegistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(control_asistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(control_asistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(control_asistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(control_asistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new control_asistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegist;
    private javax.swing.JButton btnSesion;
    private javax.swing.JLabel etiClose;
    private javax.swing.JLabel etiError;
    private javax.swing.JLabel etiEvent;
    private javax.swing.JLabel etiImagenI;
    private javax.swing.JLabel etiRest;
    private javax.swing.JLabel etimin;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToggleButton tgbtnEntrada;
    private javax.swing.JToggleButton tgbtnSalida;
    // End of variables declaration//GEN-END:variables
}
