/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Dialog;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**https://www.xvideos.com/video10848427/maria_yessenia_borracha
 *
 * @author Julian
 */
public class Login_Entrada extends JFrame {
private ImageIcon imagenInicio, imagenClose, imagenRest, imagenMin;
private Icon icono, icono_close,icono_Rest,icono_Min;
    /**
     * Creates new form Login_Entrada
     */
    public Login_Entrada() {
        initComponents();
        getContentPane().setBackground(Color.decode("#E4E4E4"));
        setLocationRelativeTo(null);

        imagenClose = new ImageIcon("src/imagenes/btnClose.png");
        icono_close = new ImageIcon(imagenClose.getImage().getScaledInstance(etiClose.getWidth(), etiClose.getHeight(), Image.SCALE_DEFAULT));
        etiClose.setIcon(icono_close);
        
        imagenRest = new ImageIcon("src/imagenes/rest.png");
        icono_Rest = new ImageIcon(imagenRest.getImage().getScaledInstance(etiRest.getWidth(), etiRest.getHeight(), Image.SCALE_DEFAULT));
        etiRest.setIcon(icono_Rest);
        
        imagenMin = new ImageIcon("src/imagenes/mini.png");
        icono_Min = new ImageIcon(imagenMin.getImage().getScaledInstance(etimin.getWidth(), etimin.getHeight(), Image.SCALE_DEFAULT));
        etimin.setIcon(icono_Min);

        jLabel11.setBackground(Color.decode("#E4E4E4"));
        jLabel9.setBackground(Color.decode("#E4E4E4"));
         btnAcep.setBackground(Color.decode("#549788"));
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        etiClose = new javax.swing.JLabel();
        etiRest = new javax.swing.JLabel();
        etimin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAcep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setModalExclusionType(null);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 520));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));

        etiClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiCloseMouseExited(evt);
            }
        });

        etiRest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiRestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiRestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiRestMouseExited(evt);
            }
        });

        etimin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiminMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(718, Short.MAX_VALUE)
                .addComponent(etimin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiRest, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etimin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiRest, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 42);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Nombre de la empresa de S.A de C.V");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 50, 600, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 11, 124, 143);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("Empleado:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(163, 11, 56, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Julian Ramirez Luis Gerardo");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(310, 30, 296, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Turno/Horario:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 60, 90, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("[09:00:00 AM - 03:00:00 PM]");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 80, 296, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("Departamento:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(160, 110, 90, 16);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Departamento de Informatica");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(310, 130, 296, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 110, 730, 180);

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Retardo");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(260, 400, 310, 30);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Hora Registrada: 09:33:24 AM");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 300, 730, 30);

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Entrada de turno:");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(260, 350, 310, 30);

        btnAcep.setText("Aceptar");
        btnAcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcepActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcep);
        btnAcep.setBounds(670, 450, 91, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void etiCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiCloseMouseClicked
       dispose();
    }//GEN-LAST:event_etiCloseMouseClicked

    private void etiCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiCloseMouseEntered
        ImageIcon imagen = new ImageIcon("src/imagenes/btnClose2.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(etiClose.getWidth(), etiClose.getHeight(), Image.SCALE_DEFAULT));
        etiClose.setIcon(icono);
    }//GEN-LAST:event_etiCloseMouseEntered

    private void etiCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiCloseMouseExited
        ImageIcon imagen = new ImageIcon("src/imagenes/btnClose.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(etiClose.getWidth(), etiClose.getHeight(), Image.SCALE_DEFAULT));
        etiClose.setIcon(icono);
    }//GEN-LAST:event_etiCloseMouseExited

    private void etiRestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiRestMouseClicked
        
    }//GEN-LAST:event_etiRestMouseClicked

    private void etiRestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiRestMouseEntered
       ImageIcon imagen = new ImageIcon("src/imagenes/rest2.png");
       Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(etiRest.getWidth(), etiRest.getHeight(), Image.SCALE_DEFAULT));
        etiRest.setIcon(icono);
    }//GEN-LAST:event_etiRestMouseEntered

    private void etiRestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiRestMouseExited
        ImageIcon imagen = new ImageIcon("src/imagenes/rest.png");
       Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(etiRest.getWidth(), etiRest.getHeight(), Image.SCALE_DEFAULT));
        etiRest.setIcon(icono);
    }//GEN-LAST:event_etiRestMouseExited

    private void etiminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiminMouseClicked
        //setExtendedState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_etiminMouseClicked

    private void etiminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiminMouseEntered
        ImageIcon imagen = new ImageIcon("src/imagenes/mini2.png");
       Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(etimin.getWidth(), etimin.getHeight(), Image.SCALE_DEFAULT));
        etimin.setIcon(icono);
    }//GEN-LAST:event_etiminMouseEntered

    private void etiminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiminMouseExited
        ImageIcon imagen = new ImageIcon("src/imagenes/mini.png");
       Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(etimin.getWidth(), etimin.getHeight(), Image.SCALE_DEFAULT));
        etimin.setIcon(icono); 
    }//GEN-LAST:event_etiminMouseExited

    private void btnAcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcepActionPerformed
      dispose();
    }//GEN-LAST:event_btnAcepActionPerformed
 
    public void llegada(boolean band){
        if(band){
            jLabel11.setText("Entrada de Turno");
            jLabel9.setVisible(true);
        }            
        else{
            jLabel11.setText("Salida de Turno");
            jLabel9.setVisible(false);
        }
            
    
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcep;
    private javax.swing.JLabel etiClose;
    private javax.swing.JLabel etiRest;
    private javax.swing.JLabel etimin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
